// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbDwhFa93yBQ6TLQSEwDBsJCkZ2SGfBgI',
    appId: '1:868767924703:web:488fa416d6180caf4b846a',
    messagingSenderId: '868767924703',
    projectId: 'just-9404a',
    authDomain: 'just-9404a.firebaseapp.com',
    storageBucket: 'just-9404a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOlDyyH0kJN3UQeSWqRjpQqwtFmYFTWeg',
    appId: '1:868767924703:android:16b1377b397f0faa4b846a',
    messagingSenderId: '868767924703',
    projectId: 'just-9404a',
    storageBucket: 'just-9404a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUJU6B4WU8RNdFcXQ18UcDhpo69sQEYWA',
    appId: '1:868767924703:ios:a4f66e516c8c98e04b846a',
    messagingSenderId: '868767924703',
    projectId: 'just-9404a',
    storageBucket: 'just-9404a.appspot.com',
    iosBundleId: 'com.example.just',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUJU6B4WU8RNdFcXQ18UcDhpo69sQEYWA',
    appId: '1:868767924703:ios:03d1e837b7beb2f24b846a',
    messagingSenderId: '868767924703',
    projectId: 'just-9404a',
    storageBucket: 'just-9404a.appspot.com',
    iosBundleId: 'com.example.just.RunnerTests',
  );
}
